apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  name: ingress
spec:
  ingressClassName: nginx
  tls:
  - hosts:
        - app.nginx.<DOMAIN>
      secretName: letsencrypt
  rules:
    rules:
  - host: app.nginx.<DOMAIN>
    http:
      paths:
      - backend:
          service:
            name: alb-demo-1
            port:
              number: 80
        path: /app1
        pathType: Prefix
      - backend:
          service:
            name: alb-demo-2
            port:
              number: 80
        path: /app2
        pathType: Prefix
      - backend:
          service:
            name: alb-demo-2
            port:
              name: http
        path: /
        pathType: Prefix
