// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yandex/cloud/validation.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_yandex_2fcloud_2fvalidation_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_yandex_2fcloud_2fvalidation_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3015000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3015008 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/descriptor.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_yandex_2fcloud_2fvalidation_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_yandex_2fcloud_2fvalidation_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_yandex_2fcloud_2fvalidation_2eproto;
::PROTOBUF_NAMESPACE_ID::Metadata descriptor_table_yandex_2fcloud_2fvalidation_2eproto_metadata_getter(int index);
namespace yandex {
namespace cloud {
class MapKeySpec;
struct MapKeySpecDefaultTypeInternal;
extern MapKeySpecDefaultTypeInternal _MapKeySpec_default_instance_;
}  // namespace cloud
}  // namespace yandex
PROTOBUF_NAMESPACE_OPEN
template<> ::yandex::cloud::MapKeySpec* Arena::CreateMaybeMessage<::yandex::cloud::MapKeySpec>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace yandex {
namespace cloud {

// ===================================================================

class MapKeySpec PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:yandex.cloud.MapKeySpec) */ {
 public:
  inline MapKeySpec() : MapKeySpec(nullptr) {}
  virtual ~MapKeySpec();
  explicit constexpr MapKeySpec(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MapKeySpec(const MapKeySpec& from);
  MapKeySpec(MapKeySpec&& from) noexcept
    : MapKeySpec() {
    *this = ::std::move(from);
  }

  inline MapKeySpec& operator=(const MapKeySpec& from) {
    CopyFrom(from);
    return *this;
  }
  inline MapKeySpec& operator=(MapKeySpec&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MapKeySpec& default_instance() {
    return *internal_default_instance();
  }
  static inline const MapKeySpec* internal_default_instance() {
    return reinterpret_cast<const MapKeySpec*>(
               &_MapKeySpec_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MapKeySpec& a, MapKeySpec& b) {
    a.Swap(&b);
  }
  inline void Swap(MapKeySpec* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MapKeySpec* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MapKeySpec* New() const final {
    return CreateMaybeMessage<MapKeySpec>(nullptr);
  }

  MapKeySpec* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MapKeySpec>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MapKeySpec& from);
  void MergeFrom(const MapKeySpec& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MapKeySpec* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "yandex.cloud.MapKeySpec";
  }
  protected:
  explicit MapKeySpec(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_yandex_2fcloud_2fvalidation_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValueFieldNumber = 1,
    kPatternFieldNumber = 2,
    kLengthFieldNumber = 3,
  };
  // string value = 1;
  void clear_value();
  const std::string& value() const;
  void set_value(const std::string& value);
  void set_value(std::string&& value);
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  std::string* mutable_value();
  std::string* release_value();
  void set_allocated_value(std::string* value);
  private:
  const std::string& _internal_value() const;
  void _internal_set_value(const std::string& value);
  std::string* _internal_mutable_value();
  public:

  // string pattern = 2;
  void clear_pattern();
  const std::string& pattern() const;
  void set_pattern(const std::string& value);
  void set_pattern(std::string&& value);
  void set_pattern(const char* value);
  void set_pattern(const char* value, size_t size);
  std::string* mutable_pattern();
  std::string* release_pattern();
  void set_allocated_pattern(std::string* pattern);
  private:
  const std::string& _internal_pattern() const;
  void _internal_set_pattern(const std::string& value);
  std::string* _internal_mutable_pattern();
  public:

  // string length = 3;
  void clear_length();
  const std::string& length() const;
  void set_length(const std::string& value);
  void set_length(std::string&& value);
  void set_length(const char* value);
  void set_length(const char* value, size_t size);
  std::string* mutable_length();
  std::string* release_length();
  void set_allocated_length(std::string* length);
  private:
  const std::string& _internal_length() const;
  void _internal_set_length(const std::string& value);
  std::string* _internal_mutable_length();
  public:

  // @@protoc_insertion_point(class_scope:yandex.cloud.MapKeySpec)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr value_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr pattern_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr length_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_yandex_2fcloud_2fvalidation_2eproto;
};
// ===================================================================

static const int kExactlyOneFieldNumber = 101400;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::OneofOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< bool >, 8, false >
  exactly_one;
static const int kRequiredFieldNumber = 101501;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< bool >, 8, false >
  required;
static const int kPatternFieldNumber = 101502;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  pattern;
static const int kValueFieldNumber = 101503;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  value;
static const int kSizeFieldNumber = 101504;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  size;
static const int kLengthFieldNumber = 101505;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  length;
static const int kUniqueFieldNumber = 101506;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< bool >, 8, false >
  unique;
static const int kMapKeyFieldNumber = 101510;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::MessageTypeTraits< ::yandex::cloud::MapKeySpec >, 11, false >
  map_key;
static const int kBytesFieldNumber = 101511;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  bytes;

// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MapKeySpec

// string value = 1;
inline void MapKeySpec::clear_value() {
  value_.ClearToEmpty();
}
inline const std::string& MapKeySpec::value() const {
  // @@protoc_insertion_point(field_get:yandex.cloud.MapKeySpec.value)
  return _internal_value();
}
inline void MapKeySpec::set_value(const std::string& value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:yandex.cloud.MapKeySpec.value)
}
inline std::string* MapKeySpec::mutable_value() {
  // @@protoc_insertion_point(field_mutable:yandex.cloud.MapKeySpec.value)
  return _internal_mutable_value();
}
inline const std::string& MapKeySpec::_internal_value() const {
  return value_.Get();
}
inline void MapKeySpec::_internal_set_value(const std::string& value) {
  
  value_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void MapKeySpec::set_value(std::string&& value) {
  
  value_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:yandex.cloud.MapKeySpec.value)
}
inline void MapKeySpec::set_value(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  value_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:yandex.cloud.MapKeySpec.value)
}
inline void MapKeySpec::set_value(const char* value,
    size_t size) {
  
  value_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:yandex.cloud.MapKeySpec.value)
}
inline std::string* MapKeySpec::_internal_mutable_value() {
  
  return value_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* MapKeySpec::release_value() {
  // @@protoc_insertion_point(field_release:yandex.cloud.MapKeySpec.value)
  return value_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void MapKeySpec::set_allocated_value(std::string* value) {
  if (value != nullptr) {
    
  } else {
    
  }
  value_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:yandex.cloud.MapKeySpec.value)
}

// string pattern = 2;
inline void MapKeySpec::clear_pattern() {
  pattern_.ClearToEmpty();
}
inline const std::string& MapKeySpec::pattern() const {
  // @@protoc_insertion_point(field_get:yandex.cloud.MapKeySpec.pattern)
  return _internal_pattern();
}
inline void MapKeySpec::set_pattern(const std::string& value) {
  _internal_set_pattern(value);
  // @@protoc_insertion_point(field_set:yandex.cloud.MapKeySpec.pattern)
}
inline std::string* MapKeySpec::mutable_pattern() {
  // @@protoc_insertion_point(field_mutable:yandex.cloud.MapKeySpec.pattern)
  return _internal_mutable_pattern();
}
inline const std::string& MapKeySpec::_internal_pattern() const {
  return pattern_.Get();
}
inline void MapKeySpec::_internal_set_pattern(const std::string& value) {
  
  pattern_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void MapKeySpec::set_pattern(std::string&& value) {
  
  pattern_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:yandex.cloud.MapKeySpec.pattern)
}
inline void MapKeySpec::set_pattern(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  pattern_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:yandex.cloud.MapKeySpec.pattern)
}
inline void MapKeySpec::set_pattern(const char* value,
    size_t size) {
  
  pattern_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:yandex.cloud.MapKeySpec.pattern)
}
inline std::string* MapKeySpec::_internal_mutable_pattern() {
  
  return pattern_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* MapKeySpec::release_pattern() {
  // @@protoc_insertion_point(field_release:yandex.cloud.MapKeySpec.pattern)
  return pattern_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void MapKeySpec::set_allocated_pattern(std::string* pattern) {
  if (pattern != nullptr) {
    
  } else {
    
  }
  pattern_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), pattern,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:yandex.cloud.MapKeySpec.pattern)
}

// string length = 3;
inline void MapKeySpec::clear_length() {
  length_.ClearToEmpty();
}
inline const std::string& MapKeySpec::length() const {
  // @@protoc_insertion_point(field_get:yandex.cloud.MapKeySpec.length)
  return _internal_length();
}
inline void MapKeySpec::set_length(const std::string& value) {
  _internal_set_length(value);
  // @@protoc_insertion_point(field_set:yandex.cloud.MapKeySpec.length)
}
inline std::string* MapKeySpec::mutable_length() {
  // @@protoc_insertion_point(field_mutable:yandex.cloud.MapKeySpec.length)
  return _internal_mutable_length();
}
inline const std::string& MapKeySpec::_internal_length() const {
  return length_.Get();
}
inline void MapKeySpec::_internal_set_length(const std::string& value) {
  
  length_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void MapKeySpec::set_length(std::string&& value) {
  
  length_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:yandex.cloud.MapKeySpec.length)
}
inline void MapKeySpec::set_length(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  length_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:yandex.cloud.MapKeySpec.length)
}
inline void MapKeySpec::set_length(const char* value,
    size_t size) {
  
  length_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:yandex.cloud.MapKeySpec.length)
}
inline std::string* MapKeySpec::_internal_mutable_length() {
  
  return length_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* MapKeySpec::release_length() {
  // @@protoc_insertion_point(field_release:yandex.cloud.MapKeySpec.length)
  return length_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void MapKeySpec::set_allocated_length(std::string* length) {
  if (length != nullptr) {
    
  } else {
    
  }
  length_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), length,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:yandex.cloud.MapKeySpec.length)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace cloud
}  // namespace yandex

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_yandex_2fcloud_2fvalidation_2eproto
